ORG 1000H
PASS DB "PASS"
ACCESO DB " ACCESO PERMITIDO"
NO_ACCESO DB " ACCESO DENEGADO"
FINAL DB ?

ORG 1500H
CARACTER DB ?

ORG 2000H
MOV AH, OFFSET ACCESO - OFFSET PASS
MOV AL, 00H
MOV BX, OFFSET CARACTER
MOV CX, OFFSET PASS
MOV DL, CARACTER ;SACAR ESTO
LOOP:INT 6
MOV DL, [BX]
PUSH BX
MOV BX, CX
MOV DH, [BX]
POP BX
CMP DH, DL
JNZ DENEGADO
INC AL
INC CX
CMP AH, AL
JNZ LOOP
MOV BX, OFFSET ACCESO
MOV AL, OFFSET NO_ACCESO - OFFSET ACCESO
INT 7
JMP FIN

DENEGADO:MOV BX, OFFSET NO_ACCESO
MOV AL, OFFSET FINAL - OFFSET NO_ACCESO
INT 7
FIN: INT 0
END