HAND_DATO EQU 40H
HAND_ESTADO EQU 41H
ORG 1000H
MSJ DB "INGENIERIA E "
DB "INFORMATICA"
FIN DB ?
ORG 2000H
IN AL, HAND_ESTADO
AND AL, 7FH
OUT HAND_ESTADO, AL
MOV BX, OFFSET MSJ
MOV CL, OFFSET FIN-OFFSET MSJ
POLL: IN AL, HAND_ESTADO
AND AL, 1
JNZ POLL
MOV AL, [BX]
OUT HAND_DATO, AL
INC BX
DEC CL
JNZ POLL
INT 0
END